<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-KHONK8Q1" failures="1" tests="8" name="Amazon.Project_On_Amazon.Form_1099_NEC" time="0.013" errors="0" timestamp="2024-05-05T17:30:31 IST" skipped="1">
  <testcase classname="Amazon.Project_On_Amazon.Form_1099_NEC" name="for_1099_nec__99" time="0.007">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at Amazon.Project_On_Amazon.Form_1099_NEC.for_1099_nec__99(Form_1099_NEC.java:12)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- for_1099_nec__99 -->
  <system-out/>
  <testcase classname="Amazon.Project_On_Amazon.Form_1099_NEC" name="for_1099_nec__1" time="0.001"/>
  <system-out/>
  <testcase classname="Amazon.Project_On_Amazon.Form_1099_NEC" name="for_1099_nec" time="0.000">
    <skipped/>
  </testcase> <!-- for_1099_nec -->
  <system-out/>
  <testcase classname="Amazon.Project_On_Amazon.Form_1099_NEC" name="for_1099_nec_1" time="0.000"/>
  <system-out/>
  <testcase classname="Amazon.Project_On_Amazon.Form_1099_NEC" name="for_1099_nec_2" time="0.001"/>
  <system-out/>
  <testcase classname="Amazon.Project_On_Amazon.Form_1099_NEC" name="for_1099_nec_3" time="0.001"/>
  <system-out/>
  <testcase classname="Amazon.Project_On_Amazon.Form_1099_NEC" name="for_1099_nec_4" time="0.002"/>
  <system-out/>
  <testcase classname="Amazon.Project_On_Amazon.Form_1099_NEC" name="for_1099_nec_5" time="0.001"/>
  <system-out/>
</testsuite> <!-- Amazon.Project_On_Amazon.Form_1099_NEC -->
